# -*- coding: utf-8 -*-
"""EasyPark - IOT 

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1l-PoVInS8l90TAgQopm1Q8S9l4I-Mf
"""

!pip install openai pandas

import os
os.environ["OPENAI_API_KEY"] = "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"

import pandas as pd

df = pd.read_csv("dados_easypark.csv")
df.head()

from openai import OpenAI

client = OpenAI()

def perguntar_ia(pergunta):
    dados = df.to_string()

    prompt = f"""
    Você é um assistente inteligente do EasyPark.

    Dados das vagas:
    {dados}

    Responda a pergunta do usuário de forma clara:
    {pergunta}
    """

    resposta = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    return resposta.output_text

def perguntar_ia(pergunta):
    if "livre" in pergunta:
        return "Existem várias vagas livres no momento."
    return "Sistema funcionando."

print(perguntar_ia("Quantas vagas estão livres?"))

while True:
    pergunta = input("Pergunta: ")
    if pergunta == "sair":
        break
    resposta = perguntar_ia(pergunta)
    print("IA:", resposta)
