
"""Sprint 4 -iot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dnWeyPzdGKD04O2zbL8xgDhoy_l7atwy
"""

import os
import threading
import pandas as pd
from flask import Flask, request, jsonify
from pyngrok import ngrok
from openai import OpenAI
import oracledb

os.environ["OPENAI_API_KEY"] = "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"
NGROK_TOKEN = "3EBgiUmGRNdP8mFF7SMqzXT1fyH_3S1rSJS97gZ53vUsUC7oE"
ngrok.kill()
ngrok.set_auth_token(NGROK_TOKEN)

client = OpenAI()
app = Flask(__name__)

def get_conn():
    return oracledb.connect(
        user="rm559613",
        password="fiap25",
        dsn="oracle.fiap.com.br:1521/orcl"
    )

def consultar_ia_com_dados(pergunta):
    try:
        if os.path.exists("dados_easypark.csv"):
            df = pd.read_csv("dados_easypark.csv")
            dados_contexto = df.to_string()
        else:
            dados_contexto = "Nenhum dado de IoT disponível."

        prompt = f"Você é o assistente do EasyPark.\nDados IoT:\n{dados_contexto}\nPergunta:\n{pergunta}"

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "Assistente de estacionamento IoT."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7
        )
        return response.choices[0].message.content
    except Exception as e:
        return str(e)

@app.route('/')
def home():
    return "EasyPark API funcionando!"

@app.route('/usuarios', methods=['GET'])
def listar_usuarios():
    try:
        conn = get_conn()
        cursor = conn.cursor()
        cursor.execute("SELECT nome, email FROM USUARIO")
        dados = cursor.fetchall()
        cursor.close()
        conn.close()

        usuarios = [{"nome": u[0], "email": u[1]} for u in dados]
        return jsonify(usuarios)
    except Exception as e:
        return jsonify({"status": "erro", "detalhes": str(e)}), 500

@app.route('/login', methods=['POST'])
def login():
    dados = request.get_json() or {}
    email = dados.get('email')

    if not email:
        return jsonify({"status": "erro", "mensagem": "Email obrigatório"}), 400

    try:
        conn = get_conn()
        cursor = conn.cursor()
        cursor.execute("SELECT senha_hash FROM USUARIO WHERE email = :1", [email])
        result = cursor.fetchone()
        cursor.close()
        conn.close()

        if result:
            return jsonify({"status": "login ok"})
        else:
            return jsonify({"status": "erro login"})
    except Exception as e:
        return jsonify({"status": "erro", "detalhes": str(e)}), 500

@app.route('/ia/perguntar', methods=['POST'])
def api_perguntar_ia():
    dados = request.get_json() or {}
    pergunta = dados.get('pergunta')

    if not pergunta:
        return jsonify({"status": "erro", "mensagem": "Pergunta vazia"}), 400

    resposta_ia = consultar_ia_com_dados(pergunta)
    return jsonify({"status": "sucesso", "resposta": resposta_ia})

@app.route('/dashboard')
def dashboard():
    try:
        conn = get_conn()
        cursor = conn.cursor()
        cursor.execute("SELECT COUNT(*) FROM USUARIO")
        total = cursor.fetchone()[0]
        cursor.close()
        conn.close()

        html = f"""
        <html>
        <body style="font-family:Arial; background:#0f172a; color:white; text-align:center; padding-top:50px;">
            <h1>EasyPark Dashboard</h1>
            <h2>Usuários Cadastrados: {total}</h2>
        </body>
        </html>
        """
        return html
    except Exception as e:
        return str(e), 500

def iniciar_servidor():
    app.run(port=5000, host="0.0.0.0", use_reloader=False)

if __name__ == '__main__':
    public_url = ngrok.connect(5000)
    print(f" Link Público da API: {public_url}")
    print(f" Link do Dashboard: {public_url}/dashboard")

    thread = threading.Thread(target=iniciar_servidor)
    thread.start()
